### ISSUE TITLE
Request to add Licence

### ISSUE THREAD

**Issue by maheshwari-1153** [imandyie/react-native-airbnb-clone#14]
Hello,

I am Maheshwari from [GeekyAnts](https://geekyants.com/). We have open source website "[Start-React](https://startreact.com/)" where we add open source products which we find helpful to the community & also we provide credits to author itself.
Let me know if you are interested to showcase your product in our open source website. If yes, then I request you to add MIT or Apache Licence in your repo. 
Looking forward to hear from you.

**Comment by imandyie** [comment]
MIT license added

**Comment by maheshwari-1153** [comment]
Hello,

Thanks a lot. We have added your product in Start React
<https://startreact.com/> Website.

Best Regards,
Maheshwari Shukla
