### ISSUE TITLE
react error

### ISSUE THREAD

**Issue by GURUcle** [imandyie/react-native-airbnb-clone#3]
what command did you use to build the app?
 was react init or create?

**Comment by GURUcle** [comment]
How should i run it?

**Comment by imandyie** [comment]
you will need to open the Android project in Android Studio or the iOS in Xcode or you can do `react-native run-android` or `react-native run-ios`

**Comment by GURUcle** [comment]
So i cant run it on EXPO XDE

**Comment by GURUcle** [comment]
?

**Comment by GURUcle** [comment]
Tried running it in expo but it doesn't continue from "loading dependency
graph, done".... Really don't know how to get it to work from there...

**Comment by imandyie** [comment]
No, it will not work in Expo

**Comment by GURUcle** [comment]
Can you provide me with your whatsapp number? If you dont mind helping
through
