### ISSUE TITLE
letter erasing themselves

### ISSUE THREAD

**Issue by GURUcle** [imandyie/react-native-airbnb-clone#4]
every time i try to enter your login detail, the letters disappear... what could be wrong sir?

**Comment by soozuang** [comment]
Me too

**Comment by soozuang** [comment]
Solution:  In the file component/InputField.js, you should remove this
![image](https://user-images.githubusercontent.com/22596854/39957560-404c4308-561f-11e8-815b-373e2348491e.png)

**Comment by GURUcle** [comment]
thanx. will check

**Comment by GURUcle** [comment]
it worked thanx
